### ISSUE TITLE
Outline libraries and APIs to be used in calling system

### ISSUE THREAD

**Issue by alyg563** [alyg563/CS530Project#24]

**Comment by AlexanderRay8** [comment]
Leaving a text message is relatively simple to do through email, and python's smtp library provides a way to send emails autonomously. Use smtplib and ssl to establish a connection to gmail to send emails through. You can use the example code to send a text or email to yourself to test. To send a text through email, use the number,with area code, with @ and the website related to the service provider. Verizon's is @vtext.com for example.

[smtp_example.txt](https://github.com/alyg563/CS530Project/files/7449625/smtp_example.txt)
